site_name: 基于Github Pages 发布 MkDocs中文文档
site_url: https://github.com/llango/shadocs
site_author: llango
site_description: "基于Github Pages 发布 MkDocs中文文档。"
repo_url: "https://github.com/llango/shadocs"
copyright: "Shadocs使用证书为: <a href='https://github.com/llango/shadocs/blob/master/LICENSE.md'>MIT license</a>"

theme:
  name: null
  custom_dir: shadocs
  colorscheme: github
  highlightjs: true
  collapse_by_default: false
  include_search_page: true
  search_index_only: false
  hljs_languages:
      - yaml
      - django

nav:
    - 主页: index.md
    - 用户指南:
        - 编写文档: user-guide/writing-your-docs.md
        - 设置文档样式: user-guide/styling-your-docs.md
        - 配置文件: user-guide/configuration.md
        - 部署文档: user-guide/deploying-your-docs.md
        - 自定义主题: user-guide/custom-themes.md
        - 插件: user-guide/plugins.md
    - 关于:
        - 发行说明: about/release-notes.md
        - 贡献: about/contributing.md
        - 许可: about/license.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  
plugins:
  - search

docs_dir: source


site_dir: docs